### ISSUE TITLE
Getting screen value as null in return of client.getDesktop()

### ISSUE THREAD

**Issue by ukpillai** [sterodium/selenium-grid-extensions#42]
Hi There,

I am getting client.getDesktop() value returned as null always. Any idea why would that be so ?

"DesktopScreenRegion desktop = client.getDesktop();" 

In debug mode found following value returned for variable desktop : {screen=null, x=0, y=0, width=0, height=0, score=0.0}

Thanks.

**Comment by ukpillai** [comment]
Sorry for not going through closed issues first.I saw similar question asked earlier (https://github.com/sterodium/selenium-grid-extensions/issues/35).

I will check the solution provided there and close this issue if that resolves mine.

**Comment by ukpillai** [comment]
Unfortunately solution provided in #35 didn't resolve my issue.

I am using following versions of all jars:

All grid extensions are version 0.6 and sterodium-rmi-0.3 jar

Selenium is 2.48.2

Also do i need to upload images to remote machine, if all my images are stored in a shared drive accessible on all nodes? I have omitted the piece of code which uploads image folder to remote machine.

**Comment by ukpillai** [comment]
I am getting the below error when executing find method on 'target'.
Exception in thread "main" java.lang.IllegalArgumentException: class sun.awt.image.ByteInterleavedRaster declares multiple JSON fields named maxX
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:146)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:83)
    at com.google.gson.Gson.getAdapter(Gson.java:359)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:55)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:99)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:219)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:99)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:219)
    at com.google.gson.Gson.toJson(Gson.java:600)
    at com.google.gson.Gson.toJson(Gson.java:579)
    at com.google.gson.Gson.toJson(Gson.java:534)
    at com.google.gson.Gson.toJson(Gson.java:514)
    at io.sterodium.rmi.protocol.client.RemoteInvoker.toString(RemoteInvoker.java:67)
    at io.sterodium.rmi.protocol.client.RemoteInvoker.getMethodInvocation(RemoteInvoker.java:54)
    at io.sterodium.rmi.protocol.client.RemoteInvoker.invoke(RemoteInvoker.java:32)
    at io.sterodium.rmi.protocol.client.RemoteObjectMethodInterceptor.invoke(RemoteObjectMethodInterceptor.java:69)
    at io.sterodium.rmi.protocol.client.RemoteObjectMethodInterceptor.intercept(RemoteObjectMethodInterceptor.java:51)
    at org.sikuli.api.DesktopScreenRegion$$EnhancerByCGLIB$$b3f0f009.find(<generated>)
    at org.iwantremote.test.remotePOC.main(remotePOC.java:40)

**Comment by echoAlexey** [comment]
Hi ukpillai, thanks for contacting us!
1. If folder is available to all selenium nodes, then you may call `getTargetFactory().setImagePrefix(pathToFolder);`
   instead of  `uploadResourceBundle(path)`

Under the hood upload files are stored in temp folder and path to it set as prefix later. See 

```
public void uploadResourceBundle(String resourceBundlePath) {
        String upload = fileExtensionClient.upload(resourceBundlePath);
        LOGGER.debug("Resource bundle uploaded to " + upload);
        getTargetFactory().setImagePrefix(upload);
    }
```

Please check this way.

**Comment by ukpillai** [comment]
Hi echoAlexey, thanks I tried as suggested by you to add a setImagePrefix(folder) and unfortunately am still getting an error as before (have attached error logged below). 

Also one more thing I have noticed was 

SikuliExtensionClient client = new SikuliExtensionClient("localhost",4444,sessionId);

Here 'client' value is set as "io.sterodium.extensions.client.SikuliExtensionClient@274d27". Is this a valid value being set to this variable ? 

Please find below error i encountered :

java.lang.IllegalArgumentException: class sun.awt.image.ByteInterleavedRaster declares multiple JSON fields named maxX
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:146)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:83)
    at com.google.gson.Gson.getAdapter(Gson.java:359)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:55)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:99)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:219)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:99)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:219)
    at com.google.gson.Gson.toJson(Gson.java:600)
    at com.google.gson.Gson.toJson(Gson.java:579)
    at com.google.gson.Gson.toJson(Gson.java:534)
    at com.google.gson.Gson.toJson(Gson.java:514)
    at io.sterodium.rmi.protocol.client.RemoteInvoker.toString(RemoteInvoker.java:67)
    at io.sterodium.rmi.protocol.client.RemoteInvoker.getMethodInvocation(RemoteInvoker.java:54)
    at io.sterodium.rmi.protocol.client.RemoteInvoker.invoke(RemoteInvoker.java:32)
    at io.sterodium.rmi.protocol.client.RemoteObjectMethodInterceptor.invoke(RemoteObjectMethodInterceptor.java:69)
    at io.sterodium.rmi.protocol.client.RemoteObjectMethodInterceptor.intercept(RemoteObjectMethodInterceptor.java:51)
    at org.sikuli.api.DesktopScreenRegion$$EnhancerByCGLIB$$4105d896.find(<generated>)
    at org.iwantremote.test.remotePOC.main(remotePOC.java:41)

**Comment by ukpillai** [comment]
Hi echoAlexey, an update on the issue. 

I was able to resolve the earlier error which was "declares multiple JSON fields named maxX". 

Well, still desktop variable is {screen=null, x=0, y=0, width=0, height=0, score=0.0} and also targetFactory's folderToScan is set as NULL too.

Please find below my code snippet:

SikuliExtensionClient client = new SikuliExtensionClient("localhost",4444,sessionId);
client.getTargetFactory().setImagePrefix("my_shared_path");
TargetFactory targetFactory = client.getTargetFactory();
ImageTarget imageTarget = targetFactory.createImageTarget("Test.PNG");
DesktopScreenRegion desktop = client.getDesktop();
ScreenRegion screenRegion  = desktop.find(imageTarget);

**Comment by echoAlexey** [comment]
Hi @ukpillai 
This comment is very similar to your issue:
https://github.com/sterodium/selenium-grid-extensions/issues/35#issuecomment-155793486

I suggest trying samples to verify your setup.
https://github.com/sterodium/selenium-grid-extensions/tree/master/sample

**Comment by ukpillai** [comment]
Hi @echoAlexey 

I tried the steps mentioned in #35, mine is simple piece of code without POM.xml.

Still targetFactory's folderToScan is set as NULL.

client.getTargetFactory().setImagePrefix("my_shared_path");
TargetFactory targetFactory = client.getTargetFactory();

**Comment by echoAlexey** [comment]
Everytime you "get" Target Factory - new proxy is created.
Calls to proxy are redirected to remote target factory which is located on Selenium Node and called there. 

You don't need to check state of proxied target factory, it proxies all calls and doesn't have state.

```
 public TargetFactory getTargetFactory() {
    return navigator.createProxy(TargetFactory.class, "target-factory");
 }
```
