### ISSUE TITLE
Error: <title>Error 403 Forbidden for Proxy</title>

### ISSUE THREAD

**Issue by Anishohri** [sterodium/selenium-grid-extensions#43]
Hi

Any help on this would be greatly appreciated.

I am trying to work with sikuli and selenium Grid. did all the configuration etc and when i run i get 403 forbidden error (complete error logs below):
 io.sterodium.rmi.protocol.server.TargetServerException: Widget target-factory invocation failed (expected 200, but was 403): <html>
<head>
<title>Error 403 Forbidden for Proxy</title>
</head>
<body>
<h2>HTTP ERROR: 403</h2><pre>Forbidden for Proxy</pre>

<p>RequestURI=/grid/admin/HubRequestsProxyingServlet/session/57d73f94-f7ad-499a-9c1d-45992494af54/SikuliExtensionServlet/target-factory</p>

<p><i><small><a href="http://jetty.mortbay.org">Powered by Jetty://</a></small></i></p>
                                                

</body>
</html>

```
at io.sterodium.rmi.protocol.client.RestTransport.send(RestTransport.java:49)
at io.sterodium.rmi.protocol.client.RestClient.invoke(RestClient.java:40)
at io.sterodium.rmi.protocol.client.RemoteInvoker.invoke(RemoteInvoker.java:36)
at io.sterodium.rmi.protocol.client.RemoteObjectMethodInterceptor.invoke(RemoteObjectMethodInterceptor.java:69)
at io.sterodium.rmi.protocol.client.RemoteObjectMethodInterceptor.intercept(RemoteObjectMethodInterceptor.java:51)
at io.sterodium.extensions.node.rmi.TargetFactory$$EnhancerByCGLIB$$3278f426.createImageTarget(<generated>)
at com.newdemo.test.paam.sikuliremote.searchGoogleForSikuliLogo(sikuliremote.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```

This is the my class:
package com.newdemo.test.paam;

import com.codeborne.selenide.WebDriverRunner;

import io.sterodium.extensions.client.SikuliExtensionClient;
import io.sterodium.extensions.node.rmi.TargetFactory;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.Platform;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.sikuli.api.DesktopScreenRegion;
import org.sikuli.api.ImageTarget;
import org.sikuli.api.ScreenRegion;
import org.sikuli.api.robot.Mouse;

import java.net.MalformedURLException;
import java.net.URL;

import static com.codeborne.selenide.Selenide.open;

public class sikuliremote {

```
private static final String GOOGLE_IMAGES_BUNDLE = "/Users/anish_ohri/Desktop/image.png";
private static final String GOOGLE_IMAGES_URL = "https://images.google.com/";
private static final String SIKULI_LOGO_SEARCH = "sikuli logo";

private static final String SEARCH_FIELD_IMG = "search_field.png";
private static final String SEARCH_BUTTON_IMG = "search_button.png";
private static final String SIKULI_LOGO_IMG = "sikuli_logo.png";


@Before
public void setUp() throws MalformedURLException {
    DesiredCapabilities desiredCapabilities = firefoxWithSikuli();
    URL url = new URL(String.format("http://%s:%d/wd/hub", GridSettings.HOST, GridSettings.PORT));

    RemoteWebDriver remoteWebDriver = new RemoteWebDriver(url, desiredCapabilities);
    WebDriverRunner.setWebDriver(remoteWebDriver);
}

@After
public void tearDown() {
    WebDriverRunner.closeWebDriver();
}

private DesiredCapabilities firefoxWithSikuli() {
    DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
    desiredCapabilities.setBrowserName("firefox");
    desiredCapabilities.setPlatform(Platform.ANY);
    desiredCapabilities.setCapability("sikuliExtension", true);
    return desiredCapabilities;
}

@Test
public void searchGoogleForSikuliLogo() throws InterruptedException {
    open("http://google.com");

    String sessionId = getSessionId();
    SikuliExtensionClient sikuliExtensionClient = new SikuliExtensionClient(GridSettings.HOST, GridSettings.PORT, sessionId);
    TargetFactory targetFactory = sikuliExtensionClient.getTargetFactory();
    ImageTarget imageTarget = targetFactory.createImageTarget("/Users/anish_ohri/Desktop/image.png");

    DesktopScreenRegion desktop = sikuliExtensionClient.getDesktop();
    ScreenRegion screenRegion = desktop.find(imageTarget);

    Mouse mouse = sikuliExtensionClient.getMouse();
    mouse.click(screenRegion.getCenter());

 //   SikuliExtensionClient sikuliExtensionClient = new SikuliExtensionClient(HOST, PORT, sessionId);
   // sikuliExtensionClient.uploadResourceBundle(GOOGLE_IMAGES_BUNDLE);
    //SikuliHelper sikuliHelper = new SikuliHelper(sikuliExtensionClient);



}

private String getSessionId() {
    return ((RemoteWebDriver) WebDriverRunner.getWebDriver()).getSessionId().toString();
}
```

}

**Comment by echoAlexey** [comment]
Hi,

Did you check this?

https://github.com/sterodium/selenium-grid-extensions/issues/36

I think problem is in grid setup.

**Comment by Anishohri** [comment]
Yes.

I did that configuration in my NodeConfig.json

{
  "configuration":
  {
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
"extension.sikuliCapability": true,
    "maxSession": 5,
    "port": 5572,
    "host": 10.222.93.126,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4433,
    "hubHost": 10.222.93.126,
    "servlets":"io.sterodium.extensions.node.SikuliExtensionServlet,io.sterodium.extensions.node.upload.FileUploadServlet,io.sterodium.extensions.node.download.FileDownloadServlet"
  }
}

Logs:

java -cp "selenium-server-standalone-2.45.0.jar:all-node-extensions-0.6.jar" org.openqa.grid.selenium.GridLauncher -role node -port 5572 -nodeConfig nodeConfig.json -hub http://10.222.93.126:4433/grid/register
12:10:44.708 INFO - Launching a selenium grid node
12:10:45.033 INFO - Java: Oracle Corporation 24.65-b04
12:10:45.033 INFO - OS: Mac OS X 10.9.5 x86_64
12:10:45.037 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
12:10:45.078 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match with current platform: MAC
12:10:45.114 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:5572/wd/hub
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
12:10:45.366 INFO - started extra node servlet visible at : http://xxx:5572/extra/SikuliExtensionServlet/*
12:10:45.367 INFO - started extra node servlet visible at : http://xxx:5572/extra/FileUploadServlet/*
12:10:45.368 INFO - started extra node servlet visible at : http://xxx:5572/extra/FileDownloadServlet/*
12:10:45.368 INFO - Version Jetty/5.1.x
12:10:45.369 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
12:10:45.377 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@68d6490d
12:10:45.377 INFO - Started HttpContext[/extra,/extra]
12:10:45.378 INFO - Started HttpContext[/selenium-server,/selenium-server]
12:10:45.378 INFO - Started HttpContext[/,/]
12:10:45.378 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@66c677a7
12:10:45.378 INFO - Started HttpContext[/wd,/wd]
12:10:45.381 INFO - Started SocketListener on 0.0.0.0:5572
12:10:45.381 INFO - Started org.openqa.jetty.jetty.Server@5680a576
12:10:45.392 INFO - using the json request : {"class":"org.openqa.grid.common.RegistrationRequest","configuration":{"nodeConfig":"nodeConfig.json","extension.sikuliCapability":true,"register":true,"port":5572,"servlets":"io.sterodium.extensions.node.SikuliExtensionServlet,io.sterodium.extensions.node.upload.FileUploadServlet,io.sterodium.extensions.node.download.FileDownloadServlet","host":"10.222.93.126","proxy":"org.openqa.grid.selenium.proxy.DefaultRemoteProxy","maxSession":5,"role":"node","hubHost":"10.222.93.126","registerCycle":5000,"hub":"http://10.222.93.126:4433/grid/register","hubPort":4433,"url":"http://10.222.93.126:5572","remoteHost":"http://10.222.93.126:5572"},"capabilities":[{"platform":"MAC","seleniumProtocol":"Selenium","browserName":"*firefox","maxInstances":5},{"platform":"MAC","seleniumProtocol":"Selenium","browserName":"*googlechrome","maxInstances":5},{"platform":"MAC","seleniumProtocol":"Selenium","browserName":"*iexplore","maxInstances":1},{"platform":"MAC","seleniumProtocol":"WebDriver","browserName":"firefox","maxInstances":5},{"platform":"MAC","seleniumProtocol":"WebDriver","browserName":"chrome","maxInstances":5},{"platform":"MAC","seleniumProtocol":"WebDriver","browserName":"internet explorer","maxInstances":1}]}

this is if i try to access the URL from browser:
http://localhost:4433/grid/admin/HubRequestsProxyingServlet/session/30516921-522c-4130-a027-843e8b9e0f99/SikuliExtensionServlet/target-factory
HTTP ERROR: 400

Problem accessing /grid/admin/HubRequestsProxyingServlet/session/30516921-522c-4130-a027-843e8b9e0f99/SikuliExtensionServlet/target-factory. Reason:

```
Invalid sessionId. No active session is present for id:30516921-522c-4130-a027-843e8b9e0f99
```

Powered by Jetty://

**Comment by echoAlexey** [comment]
This url is active only when you have session open. And you shouldn't make plain get requests, instead use java client  to access it.

**Comment by Anishohri** [comment]
i understand that i have to use  java client, i was just trying to see the response via web page.

i am still stuck on with the same error.

**Comment by echoAlexey** [comment]
Hi, 

Could you please examine - https://github.com/sterodium/selenium-grid-extensions/blob/master/sample/src/main/java/io/sterodium/sample/LocalSeleniumGridLauncher.java
It launches grid with sample configuration files. Run it, then try launching basic tests in https://github.com/sterodium/selenium-grid-extensions/tree/master/sample project.

Did it succeed?

**Comment by Anishohri** [comment]
i tried with your recommendations but still get 403 error.

Then i changed the:

static final String SIKULI_EXTENSION_PATH = "grid/admin/HubRequestsProxyingServlet/session/%s/SikuliExtensionServlet";

To:

static final String SIKULI_EXTENSION_PATH = "**/wd/hub**/grid/admin/HubRequestsProxyingServlet/session/%s/SikuliExtensionServlet";

io.sterodium.rmi.protocol.server.TargetServerException: Widget target-factory invocation failed (expected 200, but was 500): {"sessionId":null,"status":13,"state":"unhandled error","value":{"message":"POST /grid/admin/HubRequestsProxyingServlet/session/f77c3063-d244-4b49-a706-97e8023a9c6e/SikuliExtensionServlet/target-factory\nBuild info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'\nSystem info: host: 'NY023PJG3QC.local', ip: '10.222.93.126', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_67'\nDriver info: driver.version: unknown","suppressed":[],"localizedMessage":"POST /grid/admin/HubRequestsProxyingServlet/session/f77c3063-d244-4b49-a706-97e8023a9c6e/SikuliExtensionServlet/target-factory\nBuild info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'\nSystem info: host: 'NY023PJG3QC.local', ip: '10.222.93.126', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_67'\nDriver info: driver.version: unknown","buildInformation":null,"cause":null,"systemInformation":"System info: host: 'NY023PJG3QC.local', ip: '10.222.93.126', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_67'","supportUrl":null,"class":"org.openqa.selenium.UnsupportedCommandException","additionalInformation":"\nDriver info: driver.version: unknown","hCode":935289429,"stackTrace":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]},"class":"org.openqa.selenium.remote.Response","hCode":1641418227}
    at io.sterodium.rmi.protocol.client.RestTransport.send(RestTransport.java:49)
    at io.sterodium.rmi.protocol.client.RestClient.invoke(RestClient.java:40)
    at io.sterodium.rmi.protocol.client.RemoteInvoker.invoke(RemoteInvoker.java:36)
    at io.sterodium.rmi.protocol.client.RemoteObjectMethodInterceptor.invoke(RemoteObjectMethodInterceptor.java:69)
    at io.sterodium.rmi.protocol.client.RemoteObjectMethodInterceptor.intercept(RemoteObjectMethodInterceptor.java:51)
    at io.sterodium.extensions.node.rmi.TargetFactory$$EnhancerByCGLIB$$2004bcff.createImageTarget(<generated>)
    at com.newdemo.test.paam.test.I_navigate_to_url(test.java:69)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

Now i am getting 500 and 403 proxy error is gone, but i get this new error. 

Any help will be greatly appreciated
