### ISSUE TITLE
FileUploadServlet throws null pointer exception

### ISSUE THREAD

**Issue by shankarkc** [sterodium/selenium-grid-extensions#46]
when i try to upload the resource bundle i hit below exception. This was working fine till yestarday...and suddenly started failing.
io.sterodium.extensions.client.upload.ResourceUploadException: Resource upload returned status 500 with message: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /grid/admin/HubRequestsProxyingServlet/session/5199d198-f795-41cc-9eed-04a22d50dbe7/FileUploadServlet. Reason:
<pre>    java.lang.NullPointerException</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>

	at io.sterodium.extensions.client.upload.ResourceUploadRequest.upload(ResourceUploadRequest.java:62)
	at io.sterodium.extensions.client.FileExtensionClient.upload(FileExtensionClient.java:45)
	at io.sterodium.extensions.client.SikuliExtensionClient.uploadResourceBundle(SikuliExtensionClient.java:55)

Anybody knows how to fix it?
Thanks
Shankar KC

**Comment by ew9001** [comment]
I am getting the same error.

HTTP ERROR 500
Problem accessing /grid/admin/HubRequestsProxyingServlet/session/a6269c64878c378a87a07581235a09d9/FileUploadServlet. Reason:

    Server Error
Caused by:
java.lang.NoSuchMethodError: org.openqa.grid.web.servlet.RegistryBasedServlet.<init>(Lorg/openqa/grid/internal/Registry;)V
	at io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet.<init>(HubRequestsProxyingServlet.java:35)
	at io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet.<init>(HubRequestsProxyingServlet.java:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.seleniumhq.jetty9.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2535)
	at org.seleniumhq.jetty9.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1326)
	at org.seleniumhq.jetty9.servlet.ServletHolder.newInstance(ServletHolder.java:1273)
	at org.seleniumhq.jetty9.servlet.ServletHolder.initServlet(ServletHolder.java:614)
	at org.seleniumhq.jetty9.servlet.ServletHolder.getServlet(ServletHolder.java:498)
	at org.seleniumhq.jetty9.servlet.ServletHolder.ensureInstance(ServletHolder.java:785)
	at org.seleniumhq.jetty9.servlet.ServletHolder.prepare(ServletHolder.java:770)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:530)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:561)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:334)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:104)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
	at java.lang.Thread.run(Thread.java:748)

**Comment by shankarkc** [comment]
Hi @ew9001 have you built latest binaries and used them. If you are using 0.6 it would not work as it does not contain my fix. Check out latest git code and build latest jars and use it.
