### ISSUE TITLE
selenium grid extension fails with JsonSyntaxException on Ubuntu linux 16.04

### ISSUE THREAD

**Issue by shankarkc** [sterodium/selenium-grid-extensions#49]
Hi I have ubuntu 16.04 OS. I have setup selenium grid on this OS. When i tried to run the sample test given I get JSON exception. Here is the call stack...
```
AILURE! - in io.sterodium.sample.test.GoogleSearchTest
searchGoogleForSikuliLogo(io.sterodium.sample.test.GoogleSearchTest)  Time elapsed: 56.319 sec  <<< ERROR!
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:387)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:189)
	at com.google.gson.Gson.fromJson(Gson.java:810)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.google.gson.Gson.fromJson(Gson.java:724)
	at com.google.gson.Gson.fromJson(Gson.java:696)
	at io.sterodium.rmi.protocol.client.RemoteInvoker.invoke(RemoteInvoker.java:42)
	at io.sterodium.rmi.protocol.client.RemoteObjectMethodInterceptor.invoke(RemoteObjectMethodInterceptor.java:69)
	at io.sterodium.rmi.protocol.client.RemoteObjectMethodInterceptor.intercept(RemoteObjectMethodInterceptor.java:51)
	at io.sterodium.extensions.node.rmi.TargetFactory$$EnhancerByCGLIB$$d9b1bea6.setImagePrefix(<generated>)
	at io.sterodium.extensions.client.SikuliExtensionClient.uploadResourceBundle(SikuliExtensionClient.java:57)
	at io.sterodium.sample.test.GoogleSearchTest.searchGoogleForSikuliLogo(GoogleSearchTest.java:34)

```
This works finee on Windows OS without any error. This is a blocker if we want to use Linux OS. Can you pls lookinto in and fix the issue?
Thanks
Shankar KC

**Comment by shankarkc** [comment]
My bad. I upgraded grid to use selenium grid extra 1.12.10 and selenium  3.0 webdriver. When that happens grid extra removed servlet tags that resulted in this issue. I am closing this.
