### ISSUE TITLE
downloading from node seems broken now

### ISSUE THREAD

**Issue by xbald** [sterodium/selenium-grid-extensions#51]
my code is like this:

String pathToFile = getDownloadFilePath() + "ffc8d939-a8e5-4fcd-949b-3fd098c1127d.mp4";
String absolutePath = new File(pathToFile).getAbsolutePath();
File download = getFileExtensionClient().download(absolutePath);
//dowloadpath on node is d:\testDownloads

the url is (from debug):
http://localhost:4433/grid/admin/HubRequestsProxyingServlet/session/e8cb79e3-3c69-4d8b-948c-5a1b85308cc0/FileDownloadServlet/d%3A%5CtestDownloads%5Cffc8d939-a8e5-4fcd-949b-3fd098c1127d.mp4

io.sterodium.extensions.client.download.FileDownloadException: Response returned code 500, with message: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /grid/admin/HubRequestsProxyingServlet/session/11ce68fc-6e20-4c49-8905-cce310581691/FileDownloadServlet/d%3A%5CtestDownloads%5Cffc8d939-a8e5-4fcd-949b-3fd098c1127d.mp4. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.lang.IllegalArgumentException: Illegal character in path at index 54: http://192.168.1.192:5555/extra/FileDownloadServlet/d:\testDownloads\ffc8d939-a8e5-4fcd-949b-3fd098c1127d.mp4
	at java.net.URI.create(Unknown Source)
	at io.sterodium.extensions.hub.proxy.client.RequestForwardingClient.createHttpRequest(RequestForwardingClient.java:64)
	at io.sterodium.extensions.hub.proxy.client.RequestForwardingClient.forwardRequest(RequestForwardingClient.java:46)
	at io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet.forwardRequest(HubRequestsProxyingServlet.java:70)
	at io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet.doGet(HubRequestsProxyingServlet.java:41)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:543)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:320)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:112)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.URISyntaxException: Illegal character in path at index 54: http://192.168.1.192:5555/extra/FileDownloadServlet/d:\testDownloads\ffc8d939-a8e5-4fcd-949b-3fd098c1127d.mp4
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.&lt;init&gt;(Unknown Source)
	... 29 more
</pre>
<h3>Caused by:</h3><pre>java.net.URISyntaxException: Illegal character in path at index 54: http://192.168.1.192:5555/extra/FileDownloadServlet/d:\testDownloads\ffc8d939-a8e5-4fcd-949b-3fd098c1127d.mp4
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.&lt;init&gt;(Unknown Source)
	at java.net.URI.create(Unknown Source)
	at io.sterodium.extensions.hub.proxy.client.RequestForwardingClient.createHttpRequest(RequestForwardingClient.java:64)
	at io.sterodium.extensions.hub.proxy.client.RequestForwardingClient.forwardRequest(RequestForwardingClient.java:46)
	at io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet.forwardRequest(HubRequestsProxyingServlet.java:70)
	at io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet.doGet(HubRequestsProxyingServlet.java:41)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:543)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:320)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:112)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Unknown Source)
</pre>
<hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.2.20.v20161216</a><hr/>

</body>
</html>

	at io.sterodium.extensions.client.download.FileDownloadRequest.download(FileDownloadRequest.java:62)
	at io.sterodium.extensions.client.FileExtensionClient.download(FileExtensionClient.java:35)
	at com.sof.aqa.base.videos.VideosTabActions.downloadAnyVideo_aroundBody94(VideosTabActions.java:643)
	at com.sof.aqa.base.videos.VideosTabActions$AjcClosure95.run(VideosTabActions.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.sof.aqa.aspects.ActionExecutionsAspect.aroundAdvice(ActionExecutionsAspect.java:92)
	at com.sof.aqa.base.videos.VideosTabActions.downloadAnyVideo(VideosTabActions.java:637)
	at com.sof.aqa.UserVideosTest.testDownLoadLink(UserVideosTest.java:335)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:197)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:175)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:209)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by DenisMyznikov** [comment]
It's way to fix the issue:
the line
io/sterodium/extensions/hub/proxy/client/RequestForwardingClient.java:65
should be changed to
URI uri = URI.create(endpoint + **URLEncoder.encode**(SeleniumSessions.trimSessionPath(request.getPathInfo())));
It works OK locally.

**Comment by echoAlexey** [comment]
Hi! You are welcome to open pull request and I will merge it ;)

Thanks!

**Comment by DenisMyznikov** [comment]
Unfortunately it was not the best solution. Files with spaces in name still cannot be downloaded.
Better solution requires changes in other methods:
io.sterodium.extensions.client.download.FileDownloadRequest#download
and
io.sterodium.extensions.node.download.FileDownloadServlet#doGet
For example, Base64.getUrlDecoder().encode/decode looks like good solution for file name to url encoding.
Also, for automated testing in grid it's necessary to have a "doDelete" file functionality also. 

All this issues together look like a feature, not just a fast fix. I have it implemented locally, however I'm not sure if it meets a pull requirements or design requirements if exist. Could you point me?

**Comment by echoAlexey** [comment]
Hi Denis, 

Your solutions sounds good. 

At the moment I have no time to contribute to this project myself, but I will be happy to accept your pull request.

Since we already have Download/Upload Servlets, you can add Delete one too to have consistent approach :)

P.S In case you have serious interest in this project, we can talk about it's future in our slack @ JUG.lv https://docs.google.com/forms/d/e/1FAIpQLSeqqR0pJNKsjpd1Ayd0UOJiMK5KGl68zeaYIJCdbl8ONboozg/viewform?c=0&w=1

**Comment by sjethvani** [comment]
@echoAlexey  I have created PR[https://github.com/sterodium/selenium-grid-extensions/pull/54](https://github.com/sterodium/selenium-grid-extensions/pull/54) to add file delete feature . Have a look and review it ...

**Comment by myznikov** [comment]
Hello again.
The **URLEncoder.encode** still doesn't work with file names containing spaces inside.
I can apply merge request with using **java.util.Base64.getUrlEncoder** enstead (but generated URL tails will not be human-readable more).
Another way - to use HTTP POST instead of GET to send parametes without restrictions.

Is one of solutions going to be OK?
