### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal character in path at index 63

### ISSUE THREAD

**Issue by narayanaavr** [sterodium/selenium-grid-extensions#53]
I was able to open Google website on remote machine but I get below error.
used selenium grid: 3.3.1
extension-proxy-0.6.jar
all-node-extensions-0.6.jar

FAILED: to
java.lang.IllegalArgumentException: Illegal character in path at index 63: /grid/admin/HubRequestsProxyingServlet/session/RemoteWebDriver: internet explorer on WINDOWS (0e86885f-bcdf-4a79-a3ae-b9e296bf1588)/FileUploadServlet
	at java.net.URI.create(URI.java:852)
	at org.apache.http.client.methods.HttpPost.<init>(HttpPost.java:76)
	at io.sterodium.extensions.client.upload.ResourceUploadRequest.upload(ResourceUploadRequest.java:46)
	at io.sterodium.extensions.client.FileExtensionClient.upload(FileExtensionClient.java:45)
	at io.sterodium.extensions.client.SikuliExtensionClient.uploadResourceBundle(SikuliExtensionClient.java:55)
	at sikuli.DemoTest.to(DemoTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.net.URISyntaxException: Illegal character in path at index 63: /grid/admin/HubRequestsProxyingServlet/session/RemoteWebDriver: internet explorer on WINDOWS (0e86885f-bcdf-4a79-a3ae-b9e296bf1588)/FileUploadServlet
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 30 more

code my below

String sessionId = getDriver().toString();
	
	getDriver().get("www.google.com");
	
    SikuliExtensionClient sikuliExtensionClient = new SikuliExtensionClient(host,port,sessionId);
	sikuliExtensionClient.uploadResourceBundle("images/google");
//	
	
	SikuliHelper sikuliHelper = new SikuliHelper(sikuliExtensionClient);
	
	UiComponent searchButton = sikuliHelper.find("google.png");
	searchButton.click();

**Comment by echoAlexey** [comment]
try version 1.0
