### ISSUE TITLE
grid extension doesnt work with grid 3.7.1+

### ISSUE THREAD

**Issue by shankarkc** [sterodium/selenium-grid-extensions#59]
I checkedout the code and updated the souce code by updating the jat ro 3.7.1 But when i try to upload the image bundle i see below call stack.
```
io.sterodium.rmi.protocol.server.TargetServerException:
Widget target-factory invocation failed (expected 200, but was 500): <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /grid/admin/HubRequestsProxyingServlet/session/585cdd9aa562af525e27a7b156a23383/SikuliExtensionServlet/target-factory. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.lang.IllegalArgumentException: MIME type may not contain reserved characters
        at org.apache.http.util.Args.check(Args.java:36)
        at org.apache.http.entity.ContentType.create(ContentType.java:206)
        at org.apache.http.entity.ContentType.create(ContentType.java:218)
        at io.sterodium.extensions.hub.proxy.client.RequestForwardingClient.createPostRequest(RequestForwardingClient.java:75)
        at io.sterodium.extensions.hub.proxy.client.RequestForwardingClient.createHttpRequest(RequestForwardingClient.java:56)
        at io.sterodium.extensions.hub.proxy.client.RequestForwardingClient.forwardRequest(RequestForwardingClient.java:46)
        at io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet.forwardRequest(HubRequestsProxyingServlet.java:69)
        at io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet.doPost(HubRequestsProxyingServlet.java:46)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:317)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:110)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.seleniumhq.jetty9.util.thread.Invocable.invokePreferred(Invocable.java:128)
        at org.seleniumhq.jetty9.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:748)
</pre>
<hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.5.v20170502</a><hr/>

</body>
</html>
```
Any pointers to resolve highly appricated. Here is the pull request https://github.com/sterodium/selenium-grid-extensions/pull/58
Thanks
Shankar KC

**Comment by shankarkc** [comment]
Here is the fix for the above issue...
https://github.com/sterodium/selenium-grid-extensions/pull/60
You can get the rootcause in the pull request.

**Comment by shankarkc** [comment]
@echoAlexey  though the fix for 3.7.1 in git source I don't see 0.7 artifacts in maven repo.   Will it take some time to get pushed there? How do I get release binaries? Can you pls help me to push this release artifacts to maven repo ?

**Comment by erenatas** [comment]
Hello, I tried to get a build with mvn install but unfortunately it failed. Will there be any updates on this project? Thanks!

**Comment by shankarkc** [comment]
I am able to build using ```mvc clean install ``` and I am using the fixed binaries with grid. What is the issue you are facing?

**Comment by echoAlexey** [comment]
should be fine in 1.0
