### ISSUE TITLE
HubRequestsProxyingServlet cannot be instantiated after upgrading from Selenium 3.7.0 to 3.11.0

### ISSUE THREAD

**Issue by braindonor** [sterodium/selenium-grid-extensions#65]
The Selenium extensions were working fine on v3.7.0, but after upgrading to v3.11.0 I'm getting HubRequestsProxyingServlet cannot be instantiated when starting the hub.  I've built & deployed the latest selenium-grid extensions.

Stack trace from hub startup:

java  -Xms1024m -Xmx1024m -cp /opt/selenium/selenium-server-standalone.jar:/opt/selenium/exten                                                                                           sion-proxy-1.0.jar  org.openqa.grid.selenium.GridLauncherV3 -role hub -hubConfig /opt/selenium                                                                                           /config.json
23:09:07.437 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.11.0', revision:                                                                                            'e59cfb3'
23:09:07.439 INFO [GridLauncherV3$2.launch] - Launching Selenium Grid hub on port 4444
23:09:07.470 WARN [ExtraServletUtil.createServlet] - The specified class : [io.sterodium.exten                                                                                           sions.hub.proxy.HubRequestsProxyingServlet] cannot be instantiated [io/sterodium/extensions/hu                                                                                           b/proxy/HubRequestsProxyingServlet]
23:09:07.470 WARN [ExtraServletUtil.createServlet] - The specified class : [io.sterodium.exten                                                                                           sions.hub.proxy.HubRequestsProxyingServlet] cannot be instantiated [io/sterodium/extensions/hu                                                                                           b/proxy/HubRequestsProxyingServlet]
2018-04-17 23:09:07.785:INFO::main: Logging initialized @668ms to org.seleniumhq.jetty9.util.l                                                                                           og.StdErrLog
23:09:07.901 INFO [Hub.start] - Selenium Grid hub is up and running
23:09:07.902 INFO [Hub.start] - Nodes should register to http://172.17.0.2:4444/grid/register/
23:09:07.902 INFO [Hub.start] - Clients should connect to http://172.17.0.2:4444/wd/hub

**Comment by braindonor** [comment]
Tested some previous versions and it's working in v3.9.1

v3.10.0 server didn't start due to a NPE:

Exception in thread "main" java.lang.NullPointerException
        at org.openqa.grid.internal.cli.GridHubCliOptions.lambda$defaults$0(GridHubCliOptions.java:52)
        at com.beust.jcommander.JCommander.initializeDefaultValue(JCommander.java:662)
        at com.beust.jcommander.JCommander.initializeDefaultValues(JCommander.java:356)
        at com.beust.jcommander.JCommander.parse(JCommander.java:339)
        at com.beust.jcommander.JCommander.parse(JCommander.java:319)
        at org.openqa.grid.internal.cli.GridHubCliOptions.parse(GridHubCliOptions.java:42)
        at org.openqa.grid.selenium.GridLauncherV3$2.<init>(GridLauncherV3.java:278)
        at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$1(GridLauncherV3.java:277)
        at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:163)
        at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:97)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:81)

**Comment by myznikov** [comment]
For 3.11.0 try to change hubConfig.json propetry from
```json
"servlets": ["io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet"]
```
to
```json
"servlet": "io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet"
```

**Comment by braindonor** [comment]
Yup, that fixed it.

Many Thanks.
